# Conclusion

This findings into the biodegradation of Ecovio\textregistered\ within simulated benthic environments provides a valuable insight into the challenges of addressing plastic pollution with biotechnological solutions. The nearly complete integrity of the recovered Ecovio\textregistered\ samples, together with a negative BOD test response, highlights the doubtful biodegradability of PLA and PBAT blends in lake and marine environments. Furthermore, this research underscores the complexity of biodegradation processes and emphasizes the need for more sophisticated analytical tools like DEM to accurately predict and manage the fate of emerging materials. While, DEM demonstrated improved accuracy in characterizing the biodegradation kinetics compared to traditional SEM, the limited time scope of the test, should be taken with care. Moreover, a truly effective strategy requires a multifaceted approach encompassing reduced plastic production, improved waste management, and a fundamental shift towards circular economy. Without a fundamental shift in these priorities, the promise of compostable plastics like Ecovio\textregistered\ will ultimately fall short, continued research must focus not only on optimizing their biodegradability but also on addressing the broader systemic issues driving the overwhelming accumulation of plastic in our oceans.

## Declaration of competing interest {.unlisted .unnumbered}

The authors declare that they have no known competing financial interests or personal relationships that could have appeared to influence the work reported in this thesis.

## Acknowledgements {.unlisted .unnumbered}



