project:
  type: book
  output-dir: .
  execute-dir: project

book:
  output-file: "bachelor-thesis"
  title: "Are 'bioplastics' a solution to plastic pollution in the ocean?"
  subtitle: |
    Laboratory testing of Ecovio\textsuperscript{\textregistered}
    compostable plastic potential biodegradation in lake and marine
    benthic environments
  author: "Vera Gómez-Limón Gallardo"
  date: last-modified
  chapters:
    - index.qmd
    - chapters/intro.qmd
    - chapters/methods.qmd
    - chapters/results.qmd
    - chapters/discussion.qmd
    - chapters/conclusion.qmd
    - chapters/references.qmd

bibliography: references.bib
csl: apa.csl

format:
  pdf:
    documentclass: scrbook
    classoption: ["oneside", "open=any"]
    papersize: a4
    mainfont: "Times New Roman"
    geometry:
      - left=3.0cm
      - right=3.0cm
      - top=3.5cm
      - bottom=3.5cm
    fig-pos: H
    number-sections: true
    colorlinks: true
    template-partials:
      - "latex/before-body.tex"
      - "latex/titlepage.tex" 
      - "latex/academic-info.tex"
    include-in-header: 
      - "latex/in-header.tex"

execute: 
  echo: false

