# Abstract {.unnumbered}

Plastic pollution represents an urgent concern within the context of global environmental challenges. Marine ecosystems are particularly susceptible to macro and microplastics, which tend to accumulate quickly due to environmental persistence. Macrofauna become trapped in plastic litter and suffocate as a result of accidental ingestion. Microplastics, on the other hand, have been shown to constitute an increasing toxicological and ecotoxicological danger, the implications of which are still widely unknown. The persistence of plastics in marine ecosystems is largely attributed to their resistance to biodegradation, a problem potentially addressed by replacing fossil-based plastics with novel, compostable polymers termed «bioplastics». This study performed 30-day biological oxygen demand (BOD) tests to evaluate the biodegradation of Ecovio\textregistered\ , a polylactid acid (PLA) and polybutylene adipate terephthalate (PBAT) blend, in simulated benthic environments. Water and sediment field samples were collected from La Breña Reservoir and Los Boliches Beach (Andalusia, Spain). The ultimate biodegradability (BOD~L~) was evaluated using a novel double exponential model (DEM), comparing its accuracy to a classic single exponential model (SEM) using the Akaike information criterion (AIC). After visual inspection, the recovered materials were almost completely intact, and BOD tests confirmed a negative response to mineralization. This suggests that Ecovio\textregistered\ lacks fast biodegradability in benthic environments, highlighting the limitations of relying solely on biotechnological answers to address the global plastic crisis. Moreover, DEM outperformed conventional SEM in modelling BOD curves (33% lower AIC), illustrating the complex nature of biodegradation kinetics. While attractive, these synthetic alternatives may not be sufficient to tackle the escalating problem of irreversibly flooding the ocean in plastic.

## Keywords {.unnumbered .unlisted}

Andalusia, 
BOD, Biodegradation, Greenwashing, Nonlinear models, PLA, PBAT, Planetary boundaries, Simulated environment.