# Discussion

BOD tests correlated well with the visual appearance of the recovered materials, which showed almost no signs of plastic biodegradation in both environments. In line with the results from the visual inspection, the smoothness of plastic film surfaces like that of Ecovio\textsuperscript{\textregistered} has been pointed out as a limitation to biofilm formation and biodegradation [@dang2007]. Moreover, these findings are consistent with those reviewed by @lavagnolo2024, indicating that both PLA and PBAT biodegrade poorly in the marine environment. PLA, in particular, is notoriously resistant to degradation outside of carefully controlled industrial settings and strong evidence suggests it is as persistent as conventional plastic in the marine environment [@royer2023].

Furthermore, the findings of this study provide novel evidence on PBAT lack of fast biodegradability in lake freshwater, filling the gap in the review by @lavagnolo2024. The exceptional observations of biodegradation signs in lake recovered Ecovio\textsuperscript{\textregistered} might be linked to the action of mycelial organisms like fungi capable of breaking complex chemical bonds, as proposed by @tosin2012. However, the infrequency of these observations requires further research on the exact organisms and processes involved in the biodegradation of compostable materials at La Breña Reservoir.

The lack of fast biodegradation suggests that Ecovio\textsuperscript{\textregistered} products would inevitably fragment in the marine environment into increasingly smaller bio-microplastics, presenting similar threats to marine organisms as conventional plastics [@ribba2022]. Studies have shown that these particles can disrupt nitrogen cycling in freshwater sediments [@seeley2020], cause lethal-toxicity up to 60% mortality in *Daphnia magna* [@zimmermann2020], induce anxiety-like behavior and impaired movement in *Danio reiro* fish larvae [@oliveira2021], and recude fertility rate in *Microcosmus exasperatus* tunicate [@anderson2021].

The increasing rate at which novel polymers marketed as compostable or biodegradable enter the market necessitates a critical evaluation of their environmental safety [@persson2022]. Consumers are frequently misled by certifications such as EN 13432, which only apply to performance within industrial composting facilities [@eubp2023]. This problem is exacerbated by greenwashing business practices, as they profit from widespread misinformation and consumer demand for sustainable products [@goel2021].

DEM outperformed SEM at fitting 30-day BOD curves based on AIC as performance metric. DEM was able to capture the observed initial rapid BOD rise followed by a slower, more gradual increase. This was also the case for wastewater as evidenced by @mason2006. However, the predictions of such models are to be skeptically considered, and ultimate BOD measures should not be used to replace empirical evidence from longer-term tests [@hewitt1979].

It is critical to recognize limitations, particularly those encountered while modeling the cellulose (+C) lake tests, whose BOD response was too steep to be evaluated within 30 days. There are numerous factors that might influence BOD curves, including organic matter concentration, salinity, enzymatic inhibitors, nitrogen and phosphorus availability, and microbial diversity [@siwiec2011]. Less organic matter is recommended in order to avoid excessive responses, which could be accomplished by replacing the field water samples with sterile water and artificial seawater for lake and sea, respectively [@tosin2012]. It is reasonable to believe, however, that adding another exponential term to the model would better suit an even more complex organic substrate. Consequently, future research should explore the goodness-of-fit of triple exponential models to BOD curves of longer testing periods.


